apiVersion: v1
kind: Service
metadata:
  name: ai-githeal-backend
  namespace: ai-githeal
spec:
  selector:
    app: ai-githeal-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
